version: '3'

services:
  db:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    restart: always
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  web:
    container_name: api
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always
    volumes:
      - .:/code

  adminer:
    image: adminer
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
    ports:
      - "8080:8080"
    depends_on:
      - web
      - db

volumes:
  db_data:
  static_volume:
  media_volume: